### ISSUE TITLE
Unresolved dependency:  nl.thijsbroersen#scala-js-leaflet;0.2

### ISSUE THREAD

**Issue by HueyNemud** [ThijsBroersen/scala-js-leaflet#1]
Hi
I'm getting this error when adding `" nl.thijsbroersen" %% "scala-js-leaflet" % "0.2"` to the libraryDependencies.

Is your project available from one of the default sbt repositories?

**Comment by ThijsBroersen** [comment]
Not really yet! I have it on jitpack but because I use a custom domain/organization it messes up the group name (it adds the project name to the group name). Haven't figured it out if this can be solved. I will try to publish it soon in sonatype, just need to setup Travis.

Meanwhile you can publish it locally with ```sbt publishLocal```. Same goes for the '-plugins' project. Just don't forget to include the individual js-sources to your webapp manually. I always like to load resources with SRI instead of building one big js-app.

**Comment by HueyNemud** [comment]
Great, I managed to import the dependency using publishLocal, thank you.
I've had to modify the declaration to `"nl.thijsbroersen" %%% "scala-js-leaflet" % "0.1"`  though.

Publishing this package could be very useful since there is no other up-to-date Leaflet facade available (cibotech/leaflet-facade is outdated and archived).

**Comment by ThijsBroersen** [comment]
I must have forgotten to push a tag
